### ISSUE TITLE
Support serialization/deserialization

### ISSUE THREAD

**Issue by flexd** [jackunion/gridisgood#1]
Hi,
I am in the initial process of building a dynamic dashboard type React application. As you may know, gridster.js supports serialization and loading a layout. See http://gridster.net/demos/serialize.html and http://gridster.net/demos/grid-from-serialize.html

I have not looked too much at the code base yet, but do you think this would be hard to implement in gridisgood?

**Comment by jackunion** [comment]
@flexd this can be pretty useful, I'll look into it.
Shouldn't be too difficult to implement.

**Comment by jackunion** [comment]
@flexd here you go, not sure if that's exactly what you were asking for, but if I understood you correctly, you would like a way to save and then restore the layout, so the latest changes should do the trick.

Look into [Basic usage section](https://github.com/jackunion/gridisgood#basic-usage), specifically new prop `buildFromArray` and [Serialization section](https://github.com/jackunion/gridisgood#serialization).

Hope this helps, thank you for beeing interested in this project and let me know if I got your idea right.
