### ISSUE TITLE
Row collision detection bug

### ISSUE THREAD

**Issue by ivoovi** [jackunion/gridisgood#2]
First of all great component!!
I am using it for a project and i found this bug 
 [http://jsfiddle.net/yxaaqmcg/18/](url)  - try to move block 3 onto block 2.
The column collision detection works great thou

**Comment by jackunion** [comment]
@ivoovi could you please check this out?
https://jsfiddle.net/69z2wepo/32376/

Cheers

P.S. the project is pretty much frozen, you should probably check [React-Grid-Layout](https://github.com/STRML/react-grid-layout)
